# Using shared runners
before_script:
  - mkdir .aws
  - envsubst < deploy/credentials > .aws/credentials 
  - aws ecr get-login --region $AWS_REGION --no-include-email | sh;
  
build:
  stage: build
  image: swishanalytics/kops
  services:
    - docker:stable-dind
  script:
    - aws ecr get-login --region $AWS_REGION --no-include-email | sh;
    - docker build -t $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:$CI_PIPELINE_ID .
    - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:$CI_PIPELINE_ID
  except:
    - master
    - /.*hotfix.*/

build-latest:
  stage: build
  image: swishanalytics/kops
  services:
    - docker:stable-dind
  script:
    - aws ecr get-login --region $AWS_REGION --no-include-email | sh;
    - docker build -t $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:latest -t $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:$CI_PIPELINE_ID .
    - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:$CI_PIPELINE_ID
    - docker push $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com/$CI_PROJECT_NAME:latest
  only:
    - master
    - /.*hotfix.*/